# Generated by Django 3.1.3 on 2020-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201121_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dlike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
